targets:
  $default:
    builders:
      flutter_gen_runner:
        options:
          output: lib/assets/
          line_length: 80

          parse_metadata: true

          images:
            parse_animation: true

          fonts:
              outputs:
                package_parameter_enabled: false

          assets:
            outputs:
              package_parameter_enabled: false
              directory_path_enabled: true

          integrations:
            image: true
            flutter_svg: true
            lottie: false
            rive: false
      drift_dev:
        options:
          databases:
            materium: lib/database/database.dart
          schema_dir: drift_schemas/
