name: obtainium
description: Get Android app updates straight from the source.
publish_to: none

# The following defines the version and build number for the application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.7+2323

workspace:
  - dynamic_color
  - dynamic_color/example
  - layout
  - material
  - material_color_utilities
  - obtainium_fonts
  - obtainium_i18n
  - obtainium_tools

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dynamic_color:
    path: dynamic_color
  layout:
    path: layout
  material:
    path: material
  obtainium_fonts:
    path: obtainium_fonts
  obtainium_i18n:
    path: obtainium_i18n
  meta: ^1.17.0
  path_provider: ^2.1.5
  flutter_fgbg: ^0.7.1
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.5+1
  http: ^1.5.0
  webview_flutter: ^4.13.0
  html: ^0.15.6
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  device_info_plus: ^12.2.0
  file_picker: ^10.3.3
  android_package_installer: # TODO: See if PR will be accepted (dev may not be active), else remove this comment
    git:
      url: https://github.com/ImranR98/android_package_installer
      ref: main
  android_package_manager: # TODO: Make PR and switch to upstream
    git:
      url: https://github.com/ImranR98/android_package_manager
      ref: master
  share_plus: ^12.0.1
  sqflite: ^2.4.2
  easy_localization: ^3.0.8
  android_intent_plus: ^6.0.0
  flutter_archive: ^6.0.3
  hsluv: ^1.1.3
  connectivity_plus: ^7.0.0
  shared_storage: # TODO: Is this maintained?
    git:
      url: https://github.com/AlexBacich/shared-storage
      ref: master
  crypto: ^3.0.6
  bcrypt: ^1.1.3
  app_links: ^6.4.1
  background_fetch: ^1.4.0
  equations: ^5.0.2
  flex_color_picker: ^3.7.1
  android_system_font:
    git:
      url: https://github.com/re7gog/android_system_font
      ref: master
  shizuku_apk_installer:
    git:
      url: https://github.com/wilver06w/shizuku_apk_installer
      ref: master
  markdown: ^7.3.0
  flutter_typeahead: ^5.2.0
  battery_plus: ^7.0.0
  flutter_charset_detector: ^5.0.0

  flutter_foreground_task: ^9.1.0
  material_symbols_icons: ^4.2874.0
  gpt_markdown: ^1.1.4
  flutter_md: ^0.0.8
  flutter_markdown_plus: ^1.0.5
  skeletonizer: ^2.1.0+1
  super_keyboard: ^0.2.2
  super_editor: ^0.3.0-dev.35
  super_editor_markdown: ^0.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.1
  vector_graphics: ^1.1.19
  collection: ^1.19.1
  nested_scroll_view_plus: ^3.0.0
  syntax_highlight: ^0.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  flutter_gen_runner: ^5.12.0

dependency_overrides:
  material_color_utilities: ^0.13.0
  meta: ^1.17.0

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/graphics/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/translations/
    - assets/graphics/
    - assets/ca/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
