name: material_color_utilities_dart
description: A starting point for Dart libraries or applications.
version: 0.14.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
