targets:
  $default:
    builders:
      flutter_gen_runner:
        options:
          output: lib/src/assets/
          line_length: 80

          parse_metadata: true

          assets:
            outputs:
              class_name: Assets
              package_parameter_enabled: true
              directory_path_enabled: true

          fonts:
              outputs:
                class_name: Fonts
                package_parameter_enabled: true

          integrations:
            image: false
            flutter_svg: false
            lottie: false
            rive: false
