// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_DynamicTonalPalette _$DynamicTonalPaletteFromJson(Map<String, dynamic> json) =>
    _DynamicTonalPalette(
      neutral100: (json['neutral_100'] as num?)?.toInt(),
      neutral99: (json['neutral_99'] as num?)?.toInt(),
      neutral98: (json['neutral_98'] as num?)?.toInt(),
      neutral96: (json['neutral_96'] as num?)?.toInt(),
      neutral95: (json['neutral_95'] as num?)?.toInt(),
      neutral94: (json['neutral_94'] as num?)?.toInt(),
      neutral92: (json['neutral_92'] as num?)?.toInt(),
      neutral90: (json['neutral_90'] as num?)?.toInt(),
      neutral87: (json['neutral_87'] as num?)?.toInt(),
      neutral80: (json['neutral_80'] as num?)?.toInt(),
      neutral70: (json['neutral_70'] as num?)?.toInt(),
      neutral60: (json['neutral_60'] as num?)?.toInt(),
      neutral50: (json['neutral_50'] as num?)?.toInt(),
      neutral40: (json['neutral_40'] as num?)?.toInt(),
      neutral30: (json['neutral_30'] as num?)?.toInt(),
      neutral24: (json['neutral_24'] as num?)?.toInt(),
      neutral22: (json['neutral_22'] as num?)?.toInt(),
      neutral20: (json['neutral_20'] as num?)?.toInt(),
      neutral17: (json['neutral_17'] as num?)?.toInt(),
      neutral12: (json['neutral_12'] as num?)?.toInt(),
      neutral10: (json['neutral_10'] as num?)?.toInt(),
      neutral6: (json['neutral_6'] as num?)?.toInt(),
      neutral4: (json['neutral_4'] as num?)?.toInt(),
      neutral0: (json['neutral_0'] as num?)?.toInt(),
      neutralVariant100: (json['neutral_variant_100'] as num?)?.toInt(),
      neutralVariant99: (json['neutral_variant_99'] as num?)?.toInt(),
      neutralVariant98: (json['neutral_variant_98'] as num?)?.toInt(),
      neutralVariant96: (json['neutral_variant_96'] as num?)?.toInt(),
      neutralVariant95: (json['neutral_variant_95'] as num?)?.toInt(),
      neutralVariant94: (json['neutral_variant_94'] as num?)?.toInt(),
      neutralVariant92: (json['neutral_variant_92'] as num?)?.toInt(),
      neutralVariant90: (json['neutral_variant_90'] as num?)?.toInt(),
      neutralVariant87: (json['neutral_variant_87'] as num?)?.toInt(),
      neutralVariant80: (json['neutral_variant_80'] as num?)?.toInt(),
      neutralVariant70: (json['neutral_variant_70'] as num?)?.toInt(),
      neutralVariant60: (json['neutral_variant_60'] as num?)?.toInt(),
      neutralVariant50: (json['neutral_variant_50'] as num?)?.toInt(),
      neutralVariant40: (json['neutral_variant_40'] as num?)?.toInt(),
      neutralVariant30: (json['neutral_variant_30'] as num?)?.toInt(),
      neutralVariant24: (json['neutral_variant_24'] as num?)?.toInt(),
      neutralVariant22: (json['neutral_variant_22'] as num?)?.toInt(),
      neutralVariant20: (json['neutral_variant_20'] as num?)?.toInt(),
      neutralVariant17: (json['neutral_variant_17'] as num?)?.toInt(),
      neutralVariant12: (json['neutral_variant_12'] as num?)?.toInt(),
      neutralVariant10: (json['neutral_variant_10'] as num?)?.toInt(),
      neutralVariant6: (json['neutral_variant_6'] as num?)?.toInt(),
      neutralVariant4: (json['neutral_variant_4'] as num?)?.toInt(),
      neutralVariant0: (json['neutral_variant_0'] as num?)?.toInt(),
      primary100: (json['primary_100'] as num?)?.toInt(),
      primary99: (json['primary_99'] as num?)?.toInt(),
      primary95: (json['primary_95'] as num?)?.toInt(),
      primary90: (json['primary_90'] as num?)?.toInt(),
      primary80: (json['primary_80'] as num?)?.toInt(),
      primary70: (json['primary_70'] as num?)?.toInt(),
      primary60: (json['primary_60'] as num?)?.toInt(),
      primary50: (json['primary_50'] as num?)?.toInt(),
      primary40: (json['primary_40'] as num?)?.toInt(),
      primary30: (json['primary_30'] as num?)?.toInt(),
      primary20: (json['primary_20'] as num?)?.toInt(),
      primary10: (json['primary_10'] as num?)?.toInt(),
      primary0: (json['primary_0'] as num?)?.toInt(),
      secondary100: (json['secondary_100'] as num?)?.toInt(),
      secondary99: (json['secondary_99'] as num?)?.toInt(),
      secondary95: (json['secondary_95'] as num?)?.toInt(),
      secondary90: (json['secondary_90'] as num?)?.toInt(),
      secondary80: (json['secondary_80'] as num?)?.toInt(),
      secondary70: (json['secondary_70'] as num?)?.toInt(),
      secondary60: (json['secondary_60'] as num?)?.toInt(),
      secondary50: (json['secondary_50'] as num?)?.toInt(),
      secondary40: (json['secondary_40'] as num?)?.toInt(),
      secondary30: (json['secondary_30'] as num?)?.toInt(),
      secondary20: (json['secondary_20'] as num?)?.toInt(),
      secondary10: (json['secondary_10'] as num?)?.toInt(),
      secondary0: (json['secondary_0'] as num?)?.toInt(),
      tertiary100: (json['tertiary_100'] as num?)?.toInt(),
      tertiary99: (json['tertiary_99'] as num?)?.toInt(),
      tertiary95: (json['tertiary_95'] as num?)?.toInt(),
      tertiary90: (json['tertiary_90'] as num?)?.toInt(),
      tertiary80: (json['tertiary_80'] as num?)?.toInt(),
      tertiary70: (json['tertiary_70'] as num?)?.toInt(),
      tertiary60: (json['tertiary_60'] as num?)?.toInt(),
      tertiary50: (json['tertiary_50'] as num?)?.toInt(),
      tertiary40: (json['tertiary_40'] as num?)?.toInt(),
      tertiary30: (json['tertiary_30'] as num?)?.toInt(),
      tertiary20: (json['tertiary_20'] as num?)?.toInt(),
      tertiary10: (json['tertiary_10'] as num?)?.toInt(),
      tertiary0: (json['tertiary_0'] as num?)?.toInt(),
      error100: (json['error_100'] as num?)?.toInt(),
      error99: (json['error_99'] as num?)?.toInt(),
      error95: (json['error_95'] as num?)?.toInt(),
      error90: (json['error_90'] as num?)?.toInt(),
      error80: (json['error_80'] as num?)?.toInt(),
      error70: (json['error_70'] as num?)?.toInt(),
      error60: (json['error_60'] as num?)?.toInt(),
      error50: (json['error_50'] as num?)?.toInt(),
      error40: (json['error_40'] as num?)?.toInt(),
      error30: (json['error_30'] as num?)?.toInt(),
      error20: (json['error_20'] as num?)?.toInt(),
      error10: (json['error_10'] as num?)?.toInt(),
      error0: (json['error_0'] as num?)?.toInt(),
    );

_DynamicColorSchemes _$DynamicColorSchemesFromJson(Map<String, dynamic> json) =>
    _DynamicColorSchemes(
      light: DynamicColorScheme.fromJson(json['light'] as Map<String, dynamic>),
      dark: DynamicColorScheme.fromJson(json['dark'] as Map<String, dynamic>),
    );

_DynamicColorScheme _$DynamicColorSchemeFromJson(
  Map<String, dynamic> json,
) => _DynamicColorScheme(
  primaryPaletteKeyColor: (json['primary_palette_key_color'] as num?)?.toInt(),
  secondaryPaletteKeyColor: (json['secondary_palette_key_color'] as num?)
      ?.toInt(),
  tertiaryPaletteKeyColor: (json['tertiary_palette_key_color'] as num?)
      ?.toInt(),
  neutralPaletteKeyColor: (json['neutral_palette_key_color'] as num?)?.toInt(),
  neutralVariantPaletteKeyColor:
      (json['neutral_variant_palette_key_color'] as num?)?.toInt(),
  errorPaletteKeyColor: (json['error_palette_key_color'] as num?)?.toInt(),
  background: (json['background'] as num?)?.toInt(),
  onBackground: (json['on_background'] as num?)?.toInt(),
  surface: (json['surface'] as num?)?.toInt(),
  surfaceDim: (json['surface_dim'] as num?)?.toInt(),
  surfaceBright: (json['surface_bright'] as num?)?.toInt(),
  surfaceContainerLowest: (json['surface_container_lowest'] as num?)?.toInt(),
  surfaceContainerLow: (json['surface_container_low'] as num?)?.toInt(),
  surfaceContainer: (json['surface_container'] as num?)?.toInt(),
  surfaceContainerHigh: (json['surface_container_high'] as num?)?.toInt(),
  surfaceContainerHighest: (json['surface_container_highest'] as num?)?.toInt(),
  onSurface: (json['on_surface'] as num?)?.toInt(),
  surfaceVariant: (json['surface_variant'] as num?)?.toInt(),
  onSurfaceVariant: (json['on_surface_variant'] as num?)?.toInt(),
  outline: (json['outline'] as num?)?.toInt(),
  outlineVariant: (json['outline_variant'] as num?)?.toInt(),
  inverseSurface: (json['inverse_surface'] as num?)?.toInt(),
  inverseOnSurface: (json['inverse_on_surface'] as num?)?.toInt(),
  shadow: (json['shadow'] as num?)?.toInt(),
  scrim: (json['scrim'] as num?)?.toInt(),
  surfaceTint: (json['surface_tint'] as num?)?.toInt(),
  primary: (json['primary'] as num?)?.toInt(),
  primaryDim: (json['primary_dim'] as num?)?.toInt(),
  onPrimary: (json['on_primary'] as num?)?.toInt(),
  primaryContainer: (json['primary_container'] as num?)?.toInt(),
  onPrimaryContainer: (json['on_primary_container'] as num?)?.toInt(),
  primaryFixed: (json['primary_fixed'] as num?)?.toInt(),
  primaryFixedDim: (json['primary_fixed_dim'] as num?)?.toInt(),
  onPrimaryFixed: (json['on_primary_fixed'] as num?)?.toInt(),
  onPrimaryFixedVariant: (json['on_primary_fixed_variant'] as num?)?.toInt(),
  inversePrimary: (json['inverse_primary'] as num?)?.toInt(),
  secondary: (json['secondary'] as num?)?.toInt(),
  secondaryDim: (json['secondary_dim'] as num?)?.toInt(),
  onSecondary: (json['on_secondary'] as num?)?.toInt(),
  secondaryContainer: (json['secondary_container'] as num?)?.toInt(),
  onSecondaryContainer: (json['on_secondary_container'] as num?)?.toInt(),
  secondaryFixed: (json['secondary_fixed'] as num?)?.toInt(),
  secondaryFixedDim: (json['secondary_fixed_dim'] as num?)?.toInt(),
  onSecondaryFixed: (json['on_secondary_fixed'] as num?)?.toInt(),
  onSecondaryFixedVariant: (json['on_secondary_fixed_variant'] as num?)
      ?.toInt(),
  tertiary: (json['tertiary'] as num?)?.toInt(),
  tertiaryDim: (json['tertiary_dim'] as num?)?.toInt(),
  onTertiary: (json['on_tertiary'] as num?)?.toInt(),
  tertiaryContainer: (json['tertiary_container'] as num?)?.toInt(),
  onTertiaryContainer: (json['on_tertiary_container'] as num?)?.toInt(),
  tertiaryFixed: (json['tertiary_fixed'] as num?)?.toInt(),
  tertiaryFixedDim: (json['tertiary_fixed_dim'] as num?)?.toInt(),
  onTertiaryFixed: (json['on_tertiary_fixed'] as num?)?.toInt(),
  onTertiaryFixedVariant: (json['on_tertiary_fixed_variant'] as num?)?.toInt(),
  error: (json['error'] as num?)?.toInt(),
  errorDim: (json['error_dim'] as num?)?.toInt(),
  onError: (json['on_error'] as num?)?.toInt(),
  errorContainer: (json['error_container'] as num?)?.toInt(),
  onErrorContainer: (json['on_error_container'] as num?)?.toInt(),
  controlActivated: (json['control_activated'] as num?)?.toInt(),
  controlNormal: (json['control_normal'] as num?)?.toInt(),
  controlHighlight: (json['control_highlight'] as num?)?.toInt(),
  textPrimaryInverse: (json['text_primary_inverse'] as num?)?.toInt(),
  textSecondaryAndTertiaryInverse:
      (json['text_secondary_and_tertiary_inverse'] as num?)?.toInt(),
  textPrimaryInverseDisableOnly:
      (json['text_primary_inverse_disable_only'] as num?)?.toInt(),
  textSecondaryAndTertiaryInverseDisabled:
      (json['text_secondary_and_tertiary_inverse_disabled'] as num?)?.toInt(),
  textHintInverse: (json['text_hint_inverse'] as num?)?.toInt(),
);
