// ignore_for_file: invalid_annotation_target
import 'package:freezed_annotation/freezed_annotation.dart';

part 'json.freezed.dart';
part 'json.g.dart';

@freezed
abstract class DynamicTonalPalette with _$DynamicTonalPalette {
  const DynamicTonalPalette._();

  @JsonSerializable(includeIfNull: false)
  const factory DynamicTonalPalette({
    @JsonKey(name: "neutral_100") int? neutral100,
    @JsonKey(name: "neutral_99") int? neutral99,
    @JsonKey(name: "neutral_98") int? neutral98,
    @JsonKey(name: "neutral_96") int? neutral96,
    @JsonKey(name: "neutral_95") int? neutral95,
    @JsonKey(name: "neutral_94") int? neutral94,
    @JsonKey(name: "neutral_92") int? neutral92,
    @JsonKey(name: "neutral_90") int? neutral90,
    @JsonKey(name: "neutral_87") int? neutral87,
    @JsonKey(name: "neutral_80") int? neutral80,
    @JsonKey(name: "neutral_70") int? neutral70,
    @JsonKey(name: "neutral_60") int? neutral60,
    @JsonKey(name: "neutral_50") int? neutral50,
    @JsonKey(name: "neutral_40") int? neutral40,
    @JsonKey(name: "neutral_30") int? neutral30,
    @JsonKey(name: "neutral_24") int? neutral24,
    @JsonKey(name: "neutral_22") int? neutral22,
    @JsonKey(name: "neutral_20") int? neutral20,
    @JsonKey(name: "neutral_17") int? neutral17,
    @JsonKey(name: "neutral_12") int? neutral12,
    @JsonKey(name: "neutral_10") int? neutral10,
    @JsonKey(name: "neutral_6") int? neutral6,
    @JsonKey(name: "neutral_4") int? neutral4,
    @JsonKey(name: "neutral_0") int? neutral0,
    @JsonKey(name: "neutral_variant_100") int? neutralVariant100,
    @JsonKey(name: "neutral_variant_99") int? neutralVariant99,
    @JsonKey(name: "neutral_variant_98") int? neutralVariant98,
    @JsonKey(name: "neutral_variant_96") int? neutralVariant96,
    @JsonKey(name: "neutral_variant_95") int? neutralVariant95,
    @JsonKey(name: "neutral_variant_94") int? neutralVariant94,
    @JsonKey(name: "neutral_variant_92") int? neutralVariant92,
    @JsonKey(name: "neutral_variant_90") int? neutralVariant90,
    @JsonKey(name: "neutral_variant_87") int? neutralVariant87,
    @JsonKey(name: "neutral_variant_80") int? neutralVariant80,
    @JsonKey(name: "neutral_variant_70") int? neutralVariant70,
    @JsonKey(name: "neutral_variant_60") int? neutralVariant60,
    @JsonKey(name: "neutral_variant_50") int? neutralVariant50,
    @JsonKey(name: "neutral_variant_40") int? neutralVariant40,
    @JsonKey(name: "neutral_variant_30") int? neutralVariant30,
    @JsonKey(name: "neutral_variant_24") int? neutralVariant24,
    @JsonKey(name: "neutral_variant_22") int? neutralVariant22,
    @JsonKey(name: "neutral_variant_20") int? neutralVariant20,
    @JsonKey(name: "neutral_variant_17") int? neutralVariant17,
    @JsonKey(name: "neutral_variant_12") int? neutralVariant12,
    @JsonKey(name: "neutral_variant_10") int? neutralVariant10,
    @JsonKey(name: "neutral_variant_6") int? neutralVariant6,
    @JsonKey(name: "neutral_variant_4") int? neutralVariant4,
    @JsonKey(name: "neutral_variant_0") int? neutralVariant0,
    @JsonKey(name: "primary_100") int? primary100,
    @JsonKey(name: "primary_99") int? primary99,
    @JsonKey(name: "primary_95") int? primary95,
    @JsonKey(name: "primary_90") int? primary90,
    @JsonKey(name: "primary_80") int? primary80,
    @JsonKey(name: "primary_70") int? primary70,
    @JsonKey(name: "primary_60") int? primary60,
    @JsonKey(name: "primary_50") int? primary50,
    @JsonKey(name: "primary_40") int? primary40,
    @JsonKey(name: "primary_30") int? primary30,
    @JsonKey(name: "primary_20") int? primary20,
    @JsonKey(name: "primary_10") int? primary10,
    @JsonKey(name: "primary_0") int? primary0,
    @JsonKey(name: "secondary_100") int? secondary100,
    @JsonKey(name: "secondary_99") int? secondary99,
    @JsonKey(name: "secondary_95") int? secondary95,
    @JsonKey(name: "secondary_90") int? secondary90,
    @JsonKey(name: "secondary_80") int? secondary80,
    @JsonKey(name: "secondary_70") int? secondary70,
    @JsonKey(name: "secondary_60") int? secondary60,
    @JsonKey(name: "secondary_50") int? secondary50,
    @JsonKey(name: "secondary_40") int? secondary40,
    @JsonKey(name: "secondary_30") int? secondary30,
    @JsonKey(name: "secondary_20") int? secondary20,
    @JsonKey(name: "secondary_10") int? secondary10,
    @JsonKey(name: "secondary_0") int? secondary0,
    @JsonKey(name: "tertiary_100") int? tertiary100,
    @JsonKey(name: "tertiary_99") int? tertiary99,
    @JsonKey(name: "tertiary_95") int? tertiary95,
    @JsonKey(name: "tertiary_90") int? tertiary90,
    @JsonKey(name: "tertiary_80") int? tertiary80,
    @JsonKey(name: "tertiary_70") int? tertiary70,
    @JsonKey(name: "tertiary_60") int? tertiary60,
    @JsonKey(name: "tertiary_50") int? tertiary50,
    @JsonKey(name: "tertiary_40") int? tertiary40,
    @JsonKey(name: "tertiary_30") int? tertiary30,
    @JsonKey(name: "tertiary_20") int? tertiary20,
    @JsonKey(name: "tertiary_10") int? tertiary10,
    @JsonKey(name: "tertiary_0") int? tertiary0,
    @JsonKey(name: "error_100") int? error100,
    @JsonKey(name: "error_99") int? error99,
    @JsonKey(name: "error_95") int? error95,
    @JsonKey(name: "error_90") int? error90,
    @JsonKey(name: "error_80") int? error80,
    @JsonKey(name: "error_70") int? error70,
    @JsonKey(name: "error_60") int? error60,
    @JsonKey(name: "error_50") int? error50,
    @JsonKey(name: "error_40") int? error40,
    @JsonKey(name: "error_30") int? error30,
    @JsonKey(name: "error_20") int? error20,
    @JsonKey(name: "error_10") int? error10,
    @JsonKey(name: "error_0") int? error0,
  }) = _DynamicTonalPalette;

  factory DynamicTonalPalette.fromJson(Map<String, Object?> json) =>
      _$DynamicTonalPaletteFromJson(json);
}

@freezed
abstract class DynamicColorSchemes with _$DynamicColorSchemes {
  const DynamicColorSchemes._();

  @JsonSerializable(fieldRename: FieldRename.snake)
  const factory DynamicColorSchemes({
    required DynamicColorScheme light,
    required DynamicColorScheme dark,
  }) = _DynamicColorSchemes;

  factory DynamicColorSchemes.fromJson(Map<String, Object?> json) =>
      _$DynamicColorSchemesFromJson(json);
}

@freezed
abstract class DynamicColorScheme with _$DynamicColorScheme {
  const DynamicColorScheme._();

  @JsonSerializable(fieldRename: FieldRename.snake, includeIfNull: false)
  const factory DynamicColorScheme({
    int? primaryPaletteKeyColor,
    int? secondaryPaletteKeyColor,
    int? tertiaryPaletteKeyColor,
    int? neutralPaletteKeyColor,
    int? neutralVariantPaletteKeyColor,
    int? errorPaletteKeyColor,
    int? background,
    int? onBackground,
    int? surface,
    int? surfaceDim,
    int? surfaceBright,
    int? surfaceContainerLowest,
    int? surfaceContainerLow,
    int? surfaceContainer,
    int? surfaceContainerHigh,
    int? surfaceContainerHighest,
    int? onSurface,
    int? surfaceVariant,
    int? onSurfaceVariant,
    int? outline,
    int? outlineVariant,
    int? inverseSurface,
    int? inverseOnSurface,
    int? shadow,
    int? scrim,
    int? surfaceTint,
    int? primary,
    int? primaryDim,
    int? onPrimary,
    int? primaryContainer,
    int? onPrimaryContainer,
    int? primaryFixed,
    int? primaryFixedDim,
    int? onPrimaryFixed,
    int? onPrimaryFixedVariant,
    int? inversePrimary,
    int? secondary,
    int? secondaryDim,
    int? onSecondary,
    int? secondaryContainer,
    int? onSecondaryContainer,
    int? secondaryFixed,
    int? secondaryFixedDim,
    int? onSecondaryFixed,
    int? onSecondaryFixedVariant,
    int? tertiary,
    int? tertiaryDim,
    int? onTertiary,
    int? tertiaryContainer,
    int? onTertiaryContainer,
    int? tertiaryFixed,
    int? tertiaryFixedDim,
    int? onTertiaryFixed,
    int? onTertiaryFixedVariant,
    int? error,
    int? errorDim,
    int? onError,
    int? errorContainer,
    int? onErrorContainer,
    int? controlActivated,
    int? controlNormal,
    int? controlHighlight,
    int? textPrimaryInverse,
    int? textSecondaryAndTertiaryInverse,
    int? textPrimaryInverseDisableOnly,
    int? textSecondaryAndTertiaryInverseDisabled,
    int? textHintInverse,
  }) = _DynamicColorScheme;

  factory DynamicColorScheme.fromJson(Map<String, Object?> json) =>
      _$DynamicColorSchemeFromJson(json);
}
